// <auto-generated />
using System;
using DesignDnaStudio.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignDnaStudio.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718120922_InitialDesignDnaSchema")]
    partial class InitialDesignDnaSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.AssessmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConsistencyScore")
                        .HasColumnType("REAL");

                    b.Property<double>("CoverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelInformationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelObservationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelWeightsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SideBias")
                        .HasColumnType("REAL");

                    b.Property<double>("SideBiasInformation")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetComparisons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.HasIndex("ParticipantId", "StudyId", "Status");

                    b.ToTable("AssessmentSessions");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.ComparisonResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsistencyProbe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftAssetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftFeatureVectorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftPreviewSpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeftPreviewType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeftStimulusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProbeOfComparisonId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResponseTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RightAssetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightFeatureVectorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightPreviewSpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RightPreviewType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RightStimulusId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkipReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TieReason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeftStimulusId");

                    b.HasIndex("ProbeOfComparisonId");

                    b.HasIndex("RightStimulusId");

                    b.HasIndex("AssessmentSessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("ComparisonResponses");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.DesignProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignBriefJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NarrativeMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawProfileJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReliabilityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceAssessmentSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssessmentSessionId");

                    b.HasIndex("StudyId");

                    b.HasIndex("ParticipantId", "StudyId", "Version")
                        .IsUnique();

                    b.ToTable("DesignProfiles");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnonymousCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousCode")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.Stimulus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AccessibilityPass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationPairKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureVectorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewSpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviewType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudyId", "SortOrder");

                    b.HasIndex("StudyId", "ContentFamily", "CalibrationPairKey");

                    b.ToTable("Stimuli");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsistencyProbeInterval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumComparisons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumComparisons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.AssessmentSession", b =>
                {
                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Participant", "Participant")
                        .WithMany("AssessmentSessions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Study", "Study")
                        .WithMany("AssessmentSessions")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.ComparisonResponse", b =>
                {
                    b.HasOne("DesignDnaStudio.Web.Data.Entities.AssessmentSession", "AssessmentSession")
                        .WithMany("Comparisons")
                        .HasForeignKey("AssessmentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Stimulus", "LeftStimulus")
                        .WithMany()
                        .HasForeignKey("LeftStimulusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDnaStudio.Web.Data.Entities.ComparisonResponse", "ProbeOfComparison")
                        .WithMany()
                        .HasForeignKey("ProbeOfComparisonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Stimulus", "RightStimulus")
                        .WithMany()
                        .HasForeignKey("RightStimulusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentSession");

                    b.Navigation("LeftStimulus");

                    b.Navigation("ProbeOfComparison");

                    b.Navigation("RightStimulus");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.DesignProfile", b =>
                {
                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Participant", "Participant")
                        .WithMany("Profiles")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDnaStudio.Web.Data.Entities.AssessmentSession", "SourceAssessmentSession")
                        .WithMany()
                        .HasForeignKey("SourceAssessmentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("SourceAssessmentSession");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.Stimulus", b =>
                {
                    b.HasOne("DesignDnaStudio.Web.Data.Entities.Study", "Study")
                        .WithMany("Stimuli")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.AssessmentSession", b =>
                {
                    b.Navigation("Comparisons");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.Participant", b =>
                {
                    b.Navigation("AssessmentSessions");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("DesignDnaStudio.Web.Data.Entities.Study", b =>
                {
                    b.Navigation("AssessmentSessions");

                    b.Navigation("Stimuli");
                });
#pragma warning restore 612, 618
        }
    }
}
