// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gtas_vpp_be.Model;

#nullable disable

namespace gtas_vpp_be.Migrations.Migrations
{
    [DbContext(typeof(VPPMigrationDbContext))]
    [Migration("20260424080008_RemoveReasonColumn")]
    partial class RemoveReasonColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P01_Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PageName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("P01_Page");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P02_Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("P02_Group");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P03_Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("P03_Component");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P04_UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LEX02_CompanyDepartmentLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P02_GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LEX02_CompanyDepartmentLocationId");

                    b.HasIndex("P02_GroupId");

                    b.ToTable("P04_UserGroup");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P01_PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P03_ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("P01_PageId");

                    b.HasIndex("P03_ComponentId");

                    b.ToTable("P05_PageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P06_GroupPageComponentMapping", b =>
                {
                    b.Property<Guid>("P02_GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P05_PageComponentMappingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MemberCompanyCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("P02_GroupId", "P05_PageComponentMappingId", "MemberCompanyCode");

                    b.HasIndex("P05_PageComponentMappingId");

                    b.ToTable("P06_GroupPageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L01_Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassModul")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("L01_Class");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L02_ClassDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassDetailCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassDetailValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtraField1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraField2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraField3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("L02_ClassDetail");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L03_VPPCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("VPPCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPPCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("L03_VPPCategory");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L04_VPP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UOMId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("VPPCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VPPCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UOMId");

                    b.HasIndex("VPPCategoryId");

                    b.ToTable("L04_VPP");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L05_VPPSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("L05_VPPSupplier");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L06_VPPSupplierMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("L04_VPPId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("L05_VPPSupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("L04_VPPId");

                    b.HasIndex("L05_VPPSupplierId");

                    b.ToTable("L06_VPPSupplierMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.LEX02_CompanyDepartmentLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LEX02Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEX02Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEX02Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LEX02_CompanyDepartmentLocation");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAdditionalOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("M")
                        .HasColumnType("int");

                    b.Property<string>("MemberCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("VPPCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VPP01_RequestHeader");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP02_RequestDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<long>("CurrentSinglePrice")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("VPP01_RequestHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VPPId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VPP01_RequestHeaderId");

                    b.HasIndex("VPPId");

                    b.ToTable("VPP02_RequestDetail");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP03_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("LogJS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("VPP01_RequestHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VPP01_RequestHeaderId");

                    b.ToTable("VPP03_Log");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P04_UserGroup", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.LEX02_CompanyDepartmentLocation", "LEX02_CompanyDepartmentLocation")
                        .WithMany("P04_UserGroups")
                        .HasForeignKey("LEX02_CompanyDepartmentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Auth.P02_Group", "P02_Group")
                        .WithMany("P04_UserGroups")
                        .HasForeignKey("P02_GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LEX02_CompanyDepartmentLocation");

                    b.Navigation("P02_Group");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.P01_Page", "P01_Page")
                        .WithMany("P05_PageComponentMappings")
                        .HasForeignKey("P01_PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Auth.P03_Component", "P03_Component")
                        .WithMany("P05_PageComponentMappings")
                        .HasForeignKey("P03_ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("P01_Page");

                    b.Navigation("P03_Component");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P06_GroupPageComponentMapping", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.P02_Group", "P02_Group")
                        .WithMany("P06_GroupPageComponentMapping")
                        .HasForeignKey("P02_GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", "P05_PageComponentMapping")
                        .WithMany("P06_GroupPageComponentMappings")
                        .HasForeignKey("P05_PageComponentMappingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("P02_Group");

                    b.Navigation("P05_PageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L02_ClassDetail", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L01_Class", "Class")
                        .WithMany("L02_ClassDetails")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L04_VPP", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L02_ClassDetail", "UOM")
                        .WithMany("VPPs_UOM")
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L03_VPPCategory", "VPPCategory")
                        .WithMany("VPPs")
                        .HasForeignKey("VPPCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UOM");

                    b.Navigation("VPPCategory");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L06_VPPSupplierMapping", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L04_VPP", "L04_VPP")
                        .WithMany("L06_VPPSupplierMappings")
                        .HasForeignKey("L04_VPPId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L05_VPPSupplier", "L05_VPPSupplier")
                        .WithMany("L06_VPPSupplierMappings")
                        .HasForeignKey("L05_VPPSupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("L04_VPP");

                    b.Navigation("L05_VPPSupplier");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP02_RequestDetail", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", "VPP01_RequestHeader")
                        .WithMany("VPP02_RequestDetails")
                        .HasForeignKey("VPP01_RequestHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L04_VPP", "VPP")
                        .WithMany()
                        .HasForeignKey("VPPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VPP");

                    b.Navigation("VPP01_RequestHeader");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP03_Log", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", "VPP01_RequestHeader")
                        .WithMany("VPP03_Logs")
                        .HasForeignKey("VPP01_RequestHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VPP01_RequestHeader");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P01_Page", b =>
                {
                    b.Navigation("P05_PageComponentMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P02_Group", b =>
                {
                    b.Navigation("P04_UserGroups");

                    b.Navigation("P06_GroupPageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P03_Component", b =>
                {
                    b.Navigation("P05_PageComponentMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", b =>
                {
                    b.Navigation("P06_GroupPageComponentMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L01_Class", b =>
                {
                    b.Navigation("L02_ClassDetails");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L02_ClassDetail", b =>
                {
                    b.Navigation("VPPs_UOM");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L03_VPPCategory", b =>
                {
                    b.Navigation("VPPs");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L04_VPP", b =>
                {
                    b.Navigation("L06_VPPSupplierMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L05_VPPSupplier", b =>
                {
                    b.Navigation("L06_VPPSupplierMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.LEX02_CompanyDepartmentLocation", b =>
                {
                    b.Navigation("P04_UserGroups");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", b =>
                {
                    b.Navigation("VPP02_RequestDetails");

                    b.Navigation("VPP03_Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
