// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gtas_vpp_be.Model;

#nullable disable

namespace gtas_vpp_be.Migrations.Migrations
{
    [DbContext(typeof(VPPMigrationDbContext))]
    partial class VPPMigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.A01_SecurityAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Action", "OccurredAtUtc")
                        .HasDatabaseName("IX_A01_Action_Occurred");

                    b.HasIndex("TargetUserId", "OccurredAtUtc")
                        .HasDatabaseName("IX_A01_Target_Occurred");

                    b.ToTable("A01_SecurityAudit");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.A02_AuthBootstrapOperation", b =>
                {
                    b.Property<string>("OperationKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("OperationKey");

                    b.HasIndex("AccountId");

                    b.ToTable("A02_AuthBootstrapOperation");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1000000000L);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("MemberCompanyCode")
                        .HasColumnType("bigint");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SessionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_AspNetUsers_EmployeeCode")
                        .HasFilter("[EmployeeCode] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_AspNetUsers_NormalizedEmail")
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P01_Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PageName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("P01_Page");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P02_Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode")
                        .IsUnique()
                        .HasDatabaseName("UX_P02_Group_GroupCode_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("P02_Group");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P03_Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("P03_Component");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P04_UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LEX02_CompanyDepartmentLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P02_GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_P04_UserGroup_OneActivePerUser")
                        .HasFilter("[IsDeleted] = 0 AND [AccountId] IS NOT NULL");

                    b.HasIndex("LEX02_CompanyDepartmentLocationId");

                    b.HasIndex("P02_GroupId");

                    b.ToTable("P04_UserGroup", t =>
                        {
                            t.HasCheckConstraint("CK_P04_UserGroup_ActivePrimaryDepartment", "[IsDeleted] = 1 OR ([AccountId] IS NOT NULL AND [UserId] = [AccountId] AND [LEX02_CompanyDepartmentLocationId] <> '00000000-0000-0000-0000-000000000000')");
                        });
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P01_PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P03_ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("P01_PageId");

                    b.HasIndex("P03_ComponentId");

                    b.ToTable("P05_PageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P06_GroupPageComponentMapping", b =>
                {
                    b.Property<Guid>("P02_GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("P05_PageComponentMappingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MemberCompanyCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("P02_GroupId", "P05_PageComponentMappingId", "MemberCompanyCode");

                    b.HasIndex("P05_PageComponentMappingId");

                    b.ToTable("P06_GroupPageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L01_Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassModul")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("L01_Class");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L02_ClassDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassDetailCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassDetailValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExtraField1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraField2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraField3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("L02_ClassDetail");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L03_VPPCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("VPPCategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPPCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("L03_VPPCategory");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L04_VPP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UOMId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("VPPCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VPPCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VPPName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("UOMId");

                    b.HasIndex("VPPCategoryId");

                    b.HasIndex("VPPCode")
                        .IsUnique()
                        .HasDatabaseName("UX_L04_VPP_VPPCode");

                    b.HasIndex("IsDeleted", "VPPCategoryId", "VPPCode")
                        .HasDatabaseName("IX_L04_VPP_Active_Category_Code");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("IsDeleted", "VPPCategoryId", "VPPCode"), new[] { "VPPName", "UOMId" });

                    b.ToTable("L04_VPP");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L05_VPPSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("L05_VPPSupplier");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L06_VPPSupplierMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("L04_VPPId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("L05_VPPSupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("L07_PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("L04_VPPId");

                    b.HasIndex("L05_VPPSupplierId");

                    b.HasIndex("L07_PriceListId", "L04_VPPId")
                        .IsUnique()
                        .HasDatabaseName("UX_L06_OneDefaultPerVPPPerList")
                        .HasFilter("[IsDefault] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("L07_PriceListId", "L04_VPPId", "IsDeleted")
                        .HasDatabaseName("IX_L06_PriceBookItem_Resolve");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("L07_PriceListId", "L04_VPPId", "IsDeleted"), new[] { "NetPrice", "VatRate", "MinimumOrderQuantity", "LeadTimeDays" });

                    b.ToTable("L06_VPPSupplierMapping", t =>
                        {
                            t.HasCheckConstraint("CK_L06_LeadTime_NonNegative", "[LeadTimeDays] >= 0");

                            t.HasCheckConstraint("CK_L06_Moq_NonNegative", "[MinimumOrderQuantity] >= 0");

                            t.HasCheckConstraint("CK_L06_Price_NonNegative", "[NetPrice] >= 0");

                            t.HasCheckConstraint("CK_L06_VatRate_Range", "[VatRate] >= 0 AND [VatRate] <= 100");
                        });
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L07_PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpiredByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LegacyBackfillStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PriceListCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PriceListName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PublishedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("RebateAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("VatPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("UX_L07_OneDefault")
                        .HasFilter("[IsDefault] = 1 AND [IsDeleted] = 0");

                    b.HasIndex("SupplierId", "PriceListCode", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_L07_PriceBook_Supplier_Version")
                        .HasFilter("[IsDeleted] = 0 AND [SupplierId] IS NOT NULL AND [PriceListCode] IS NOT NULL");

                    b.HasIndex("SupplierId", "Status", "EffectiveFromUtc", "EffectiveToUtc")
                        .HasDatabaseName("IX_L07_PriceBook_Effective");

                    b.ToTable("L07_PriceList", t =>
                        {
                            t.HasCheckConstraint("CK_L07_PriceBook_CommercialAmounts", "[RebateAmount] >= 0 AND [FeeAmount] >= 0 AND [ShippingAmount] >= 0");

                            t.HasCheckConstraint("CK_L07_PriceBook_DiscountRate", "[DiscountRate] >= 0 AND [DiscountRate] <= 100");

                            t.HasCheckConstraint("CK_L07_PriceBook_EffectiveWindow", "[EffectiveToUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc]");

                            t.HasCheckConstraint("CK_L07_PriceBook_VersionPositive", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.LEX02_CompanyDepartmentLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LEX02Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEX02Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEX02Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LEX02_CompanyDepartmentLocation");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Notifications.N01_Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Route")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MemberCompanyCode", "CorrelationId")
                        .HasDatabaseName("IX_N01_User_Company_Correlation");

                    b.HasIndex("UserId", "MemberCompanyCode", "ReadAt", "CreatedAt")
                        .HasDatabaseName("IX_N01_User_Company_Read_Created");

                    b.HasIndex("UserId", "MemberCompanyCode", "Type", "CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_N01_User_Company_Type_Correlation")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.ToTable("N01_Notification");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Notifications.N02_EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MemberCompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_N02_EmailOutbox_DeduplicationKey");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("IX_N02_EmailOutbox_Due");

                    b.ToTable("N02_EmailOutbox");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP00_Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTransitionAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastTransitionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LastTransitionUserId")
                        .HasColumnType("int");

                    b.Property<int>("M")
                        .HasColumnType("int");

                    b.Property<string>("MemberCompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDeadlineUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SupplementApprovalDeadlineUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberCompanyCode", "State", "SubmissionDeadlineUtc")
                        .HasDatabaseName("IX_VPP00_Period_Company_State_Deadline");

                    b.HasIndex("MemberCompanyCode", "Y", "M")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP00_Period_Company_Year_Month_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("VPP00_Period", t =>
                        {
                            t.HasCheckConstraint("CK_VPP00_Period_ValidRange", "[Y] BETWEEN 1 AND 9999 AND [M] BETWEEN 1 AND 12 AND [SubmissionDeadlineUtc] > [StartAtUtc] AND [SupplementApprovalDeadlineUtc] >= [SubmissionDeadlineUtc] AND [State] IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<Guid?>("BaseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseRequestSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledById")
                        .HasColumnType("int");

                    b.Property<string>("CommandPayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsAdditionalOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentRevision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("M")
                        .HasColumnType("int");

                    b.Property<string>("MemberCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedById")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestSeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SettledByPriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SettledByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SupersededByRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SupplementAttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("SupplementReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SupplementSequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("VPPCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("RequestSeriesId")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP01_CurrentRevisionSeries")
                        .HasFilter("[IsDeleted] = 0 AND [IsCurrentRevision] = 1");

                    b.HasIndex("SettledByPriceListId");

                    b.HasIndex("VPPCode")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP01_VPPCode")
                        .HasFilter("[VPPCode] IS NOT NULL");

                    b.HasIndex("CreateUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP01_IdempotencyKey")
                        .HasFilter("[IsDeleted] = 0 AND [IdempotencyKey] IS NOT NULL");

                    b.HasIndex("CreateUserId", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP01_OneRegularPerUserPeriod")
                        .HasFilter("[IsDeleted] = 0 AND [IsCurrentRevision] = 1 AND [IsAdditionalOrder] = 0");

                    b.HasIndex("CreateUserId", "PeriodId", "BaseRequestSeriesId")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP01_OnePendingSupplement")
                        .HasFilter("[IsDeleted] = 0 AND [IsCurrentRevision] = 1 AND [IsAdditionalOrder] = 1 AND [Status] = 6");

                    b.HasIndex("CreateUserId", "PeriodId", "BaseRequestSeriesId", "SupplementAttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP01_SupplementAttempt")
                        .HasFilter("[IsDeleted] = 0 AND [IsCurrentRevision] = 1 AND [IsAdditionalOrder] = 1 AND [SupplementAttemptNumber] IS NOT NULL");

                    b.HasIndex("Y", "M", "IsDeleted", "Status", "IsAdditionalOrder")
                        .HasDatabaseName("IX_VPP01_RequestHeader_Period_Status");

                    b.HasIndex("CreateUserId", "Y", "M", "IsDeleted", "IsAdditionalOrder", "Status")
                        .HasDatabaseName("IX_VPP01_RequestHeader_User_Period_Status");

                    b.ToTable("VPP01_RequestHeader");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP02_RequestDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<long>("CurrentSinglePrice")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("VPP01_RequestHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VPPId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VPP01_RequestHeaderId");

                    b.HasIndex("VPPId");

                    b.ToTable("VPP02_RequestDetail");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP03_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Action")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("LogJS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MemberCompanyCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("VPP01_RequestHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VPP01_RequestHeaderId");

                    b.ToTable("VPP03_Log");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP04_Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CommandPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfirmedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentRevision")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("M")
                        .HasColumnType("int");

                    b.Property<string>("MemberCompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PriceAsOfUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PriceListCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PriceListName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PriceListVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("PrimarySupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimarySupplierName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("RebateAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("RoundingAdjustment")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid?>("SupersededBySettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesSettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SupersedesSettlementId");

                    b.HasIndex("MemberCompanyCode", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP04_Settlement_Idempotency")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("MemberCompanyCode", "Y", "M")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP04_Settlement_Current")
                        .HasFilter("[IsDeleted] = 0 AND [IsCurrentRevision] = 1");

                    b.HasIndex("MemberCompanyCode", "Y", "M", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_VPP04_Settlement_Revision");

                    b.ToTable("VPP04_Settlement", t =>
                        {
                            t.HasCheckConstraint("CK_VPP04_Settlement_Amounts", "[Subtotal] >= 0 AND [DiscountAmount] >= 0 AND [RebateAmount] >= 0 AND [FeeAmount] >= 0 AND [ShippingAmount] >= 0 AND [VatAmount] >= 0 AND [GrandTotal] >= 0");

                            t.HasCheckConstraint("CK_VPP04_Settlement_Period", "[Y] BETWEEN 1 AND 9999 AND [M] BETWEEN 1 AND 12 AND [RevisionNumber] > 0");
                        });
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP05_SettlementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupplierException")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumOrderQuantity")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("NetUnitPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("PriceBookItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierExceptionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("VppCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("VppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VppName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "VppId")
                        .IsUnique();

                    b.ToTable("VPP05_SettlementItem", t =>
                        {
                            t.HasCheckConstraint("CK_VPP05_SettlementItem_Amounts", "[Quantity] > 0 AND [NetUnitPrice] >= 0 AND [VatRate] >= 0 AND [VatRate] <= 100 AND [NetAmount] >= 0 AND [VatAmount] >= 0 AND [GrossAmount] >= 0");
                        });
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP06_SettlementCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllocationBasis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId", "ChargeType")
                        .IsUnique();

                    b.ToTable("VPP06_SettlementCharge");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP07_SettlementAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommercialAdjustmentAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("RequestDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("RoundingAdjustment")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SettlementItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("SettlementItemId");

                    b.HasIndex("SettlementId", "DepartmentCode");

                    b.HasIndex("SettlementId", "RequestDetailId")
                        .IsUnique();

                    b.ToTable("VPP07_SettlementAllocation", t =>
                        {
                            t.HasCheckConstraint("CK_VPP07_SettlementAllocation_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.A02_AuthBootstrapOperation", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P04_UserGroup", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("gtas_vpp_be.Model.Library.LEX02_CompanyDepartmentLocation", "LEX02_CompanyDepartmentLocation")
                        .WithMany("P04_UserGroups")
                        .HasForeignKey("LEX02_CompanyDepartmentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Auth.P02_Group", "P02_Group")
                        .WithMany("P04_UserGroups")
                        .HasForeignKey("P02_GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LEX02_CompanyDepartmentLocation");

                    b.Navigation("P02_Group");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.P01_Page", "P01_Page")
                        .WithMany("P05_PageComponentMappings")
                        .HasForeignKey("P01_PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Auth.P03_Component", "P03_Component")
                        .WithMany("P05_PageComponentMappings")
                        .HasForeignKey("P03_ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("P01_Page");

                    b.Navigation("P03_Component");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P06_GroupPageComponentMapping", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Auth.P02_Group", "P02_Group")
                        .WithMany("P06_GroupPageComponentMapping")
                        .HasForeignKey("P02_GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", "P05_PageComponentMapping")
                        .WithMany("P06_GroupPageComponentMappings")
                        .HasForeignKey("P05_PageComponentMappingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("P02_Group");

                    b.Navigation("P05_PageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L02_ClassDetail", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L01_Class", "Class")
                        .WithMany("L02_ClassDetails")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L04_VPP", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L02_ClassDetail", "UOM")
                        .WithMany("VPPs_UOM")
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L03_VPPCategory", "VPPCategory")
                        .WithMany("VPPs")
                        .HasForeignKey("VPPCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UOM");

                    b.Navigation("VPPCategory");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L06_VPPSupplierMapping", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L04_VPP", "L04_VPP")
                        .WithMany("L06_VPPSupplierMappings")
                        .HasForeignKey("L04_VPPId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L05_VPPSupplier", "L05_VPPSupplier")
                        .WithMany("L06_VPPSupplierMappings")
                        .HasForeignKey("L05_VPPSupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L07_PriceList", "L07_PriceList")
                        .WithMany("L06_VPPSupplierMappings")
                        .HasForeignKey("L07_PriceListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("L04_VPP");

                    b.Navigation("L05_VPPSupplier");

                    b.Navigation("L07_PriceList");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L07_PriceList", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.Library.L05_VPPSupplier", "Supplier")
                        .WithMany("PriceBooks")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP00_Period", "Period")
                        .WithMany("RequestHeaders")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("gtas_vpp_be.Model.Library.L07_PriceList", "SettledByPriceList")
                        .WithMany()
                        .HasForeignKey("SettledByPriceListId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Period");

                    b.Navigation("SettledByPriceList");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP02_RequestDetail", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", "VPP01_RequestHeader")
                        .WithMany("VPP02_RequestDetails")
                        .HasForeignKey("VPP01_RequestHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.Library.L04_VPP", "VPP")
                        .WithMany()
                        .HasForeignKey("VPPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VPP");

                    b.Navigation("VPP01_RequestHeader");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP03_Log", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", "VPP01_RequestHeader")
                        .WithMany("VPP03_Logs")
                        .HasForeignKey("VPP01_RequestHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VPP01_RequestHeader");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP04_Settlement", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP00_Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.VPP.VPP04_Settlement", "SupersedesSettlement")
                        .WithMany()
                        .HasForeignKey("SupersedesSettlementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Period");

                    b.Navigation("SupersedesSettlement");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP05_SettlementItem", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP04_Settlement", "Settlement")
                        .WithMany("Items")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP06_SettlementCharge", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP04_Settlement", "Settlement")
                        .WithMany("Charges")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP07_SettlementAllocation", b =>
                {
                    b.HasOne("gtas_vpp_be.Model.VPP.VPP04_Settlement", "Settlement")
                        .WithMany("Allocations")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gtas_vpp_be.Model.VPP.VPP05_SettlementItem", "SettlementItem")
                        .WithMany()
                        .HasForeignKey("SettlementItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Settlement");

                    b.Navigation("SettlementItem");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P01_Page", b =>
                {
                    b.Navigation("P05_PageComponentMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P02_Group", b =>
                {
                    b.Navigation("P04_UserGroups");

                    b.Navigation("P06_GroupPageComponentMapping");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P03_Component", b =>
                {
                    b.Navigation("P05_PageComponentMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Auth.P05_PageComponentMapping", b =>
                {
                    b.Navigation("P06_GroupPageComponentMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L01_Class", b =>
                {
                    b.Navigation("L02_ClassDetails");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L02_ClassDetail", b =>
                {
                    b.Navigation("VPPs_UOM");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L03_VPPCategory", b =>
                {
                    b.Navigation("VPPs");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L04_VPP", b =>
                {
                    b.Navigation("L06_VPPSupplierMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L05_VPPSupplier", b =>
                {
                    b.Navigation("L06_VPPSupplierMappings");

                    b.Navigation("PriceBooks");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.L07_PriceList", b =>
                {
                    b.Navigation("L06_VPPSupplierMappings");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.Library.LEX02_CompanyDepartmentLocation", b =>
                {
                    b.Navigation("P04_UserGroups");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP00_Period", b =>
                {
                    b.Navigation("RequestHeaders");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP01_RequestHeader", b =>
                {
                    b.Navigation("VPP02_RequestDetails");

                    b.Navigation("VPP03_Logs");
                });

            modelBuilder.Entity("gtas_vpp_be.Model.VPP.VPP04_Settlement", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Charges");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
